FROM php:8.5-apache

# Set the working directory inside the container
WORKDIR /var/www/html

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Optional: Install common extensions (e.g., PDO MySQL)
# RUN docker-php-ext-install pdo_mysql

# Apache is already configured to expose port 80
EXPOSE 80