<?php
// File: public/01_create.php
require __DIR__ . '/../bootstrap.php';   // provides $em

use App\Entity\BookEntity;

$book = new BookEntity();
$book->setTitle('Deep Learning');
$book->setAuthor('Ian Goodfellow');
$book->setYear(2016);
$book->setIsAvailable(true);

$em->persist($book);  // tell Doctrine to track this new object
$em->flush();         // INSERT INTO books (...) VALUES (...)

echo "Saved with ID: " . $book->getId() . PHP_EOL;
// Output: Saved with ID: <auto-generated>
